<?php

namespace dao;
require_once dirname(__FILE__) . '/../../dao/DB.php';
require_once dirname(__FILE__) . '/../../dao/Filter.php';
require_once dirname(__FILE__) . '/../../dao/DB.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-17 at 20:09:48.
 */
class DBTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var DB
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new DB;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @covers dao\DB::execute
	 * @todo   Implement testExecute().
	 */
	public function testExecute()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers dao\DB::set
	 * @todo   Implement testSet().
	 */
	public function testSet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers dao\DB::data
	 * @todo   Implement testData().
	 */
	public function testData()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers dao\DB::setRowData
	 * @todo   Implement testSetRowData().
	 */
	public function testSetRowData()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers dao\DB::where
	 * @todo   Implement testWhere().
	 */
	public function testWhere()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
